Return list of LayerDataTuple instead of single layers
haesleinhuepf/napari-crop pull request #7
Opened 2021-12-28 13:26 UTC by zoccoler

I implemented these changes to try to solve #6, returning several layers for several drawn shapes, but it is still not working.

The motivation for this is explained [here](https://napari.org/guides/stable/magicgui.html?highlight=layerdatatuple#returning-list-napari-types-layerdatatuple) and there is indication that this approach has been implemented [here](https://forum.image.sc/t/problem-with-adding-multiple-layers-at-once-as-list-napari-types-layerdatatuple-to/61293).

2021-12-28 16:29 UTC, tdmorello commented
Hm, maybe it needs to be decorated with `@magic_factory` for that type annotation to work? I'm not sure.

2021-12-28 16:43 UTC, tdmorello commented
The label functionality was broken after my last PR (sorry about that!). I fixed that and added a test for it. If the output type of the crop function changes with @zoccoler 's PR, the tests will need to change. My fork makes these changes (https://github.com/tdmorello/napari-crop) but also implements @zoccoler 's multi crop idea. Not sure what you want to do @haesleinhuepf , but I can hold off on that PR until @zoccoler 's changes go through!

2021-12-28 16:54 UTC, haesleinhuepf commented
Hi Tim and Marcelo @tdmorello @zoccoler ,

bug fixes have higher priority than new features. Would you mind sending a PR with your bugfix @tdmorello ? I'd merge it right away. We can then afterwards find out how to incorporate @zoccoler's suggestion (which is great btw). There was a discussion recently in the image.sc forum about a similar issue:
https://forum.image.sc/t/problem-with-adding-multiple-layers-at-once-as-list-napari-types-layerdatatuple-to/61293

Maybe that helps :-)

Thanks!
Robert

2021-12-28 17:46 UTC, zoccoler commented
Hi Tim and Robert,

@tdmorello no problem, if #9 from your fork fix both things, we should merge there :) 
Does that implementation actually work for you? I'm refering to the multi-crop functionality by returning a list of `LayerDataTuple`. I guess it should work, but it didn't for me yet.

@haesleinhuepf that's the same link I mentioned 😅 To my best knowledge, I made the same kind of implementation, but it still returns just a single layer.

2021-12-28 17:49 UTC, zoccoler commented
The way I had done before was to add the layer inside the function before returning, that should work, but I think using annotations seems more appropriate indeed.

2021-12-28 18:21 UTC, haesleinhuepf commented on napari_crop/_function.py
>      for shape, shape_type in zip(shapes, shape_types):
```suggestion
    for count, [shape, shape_type] in enumerate(zip(shapes, shape_types)):
```

2021-12-28 18:24 UTC, haesleinhuepf requested changes
I think I made it to work. We just need to provide different names for each copied layer.

Let me know if my suggestions work for you Marcelo @zoccoler

2021-12-28 18:24 UTC, haesleinhuepf commented on napari_crop/_function.py
> +            cropped_list.append((cropped_data, layer_props, 'labels'))
```suggestion
        new_layer_props = layer_props.copy()
        new_layer_props["name"] = layer_props["name"] + f" (cropped {count+1})"
        cropped_list.append((cropped_data, new_layer_props, layer_type))
```
It turns out, we cannot pass the same identical dictionary to all new layers. It must be copies. The underlying reason is: if there are two layers with the same name, the data will be stored to the same layer. That's why I was adding a number to the name.
Furthermore, the two `if`-statements were not necessary. We can pass the type-string as parameter as it is.

2021-12-28 18:56 UTC, zoccoler commented on napari_crop/_function.py
> +            cropped_list.append((cropped_data, layer_props, 'labels'))
Nice @haesleinhuepf ! It works here!
I am going to commit changes and, if that's OK, merge it afterwards.

2021-12-28 19:01 UTC, zoccoler commented
I can't merge because I don't have write access to the repository. @haesleinhuepf

2021-12-28 20:41 UTC, haesleinhuepf approved these changes

2021-12-28 20:49 UTC, haesleinhuepf commented
Hi Marcelo @zoccoler ,

thanks for implementing this. That was actually some feature I was thinking of from the beginning and never found time for implementing it. I'm glad you did it, :-)

Would you mind checking why the tests are failing at the moment? You can run them locally using `pytest`  and read some details about napari plugin testing [here](https://napari.org/plugins/stable/best_practices.html#write-extensive-tests-for-your-plugin). Furthermore, would you please add a simple test for the new feature? I'd say a test where two squares are cropped and afterwards, it's tested if the resulting layer list contains two elements would be enough.

I will then merge it happily :-)

Thanks!
Robert

2021-12-28 20:54 UTC, tdmorello commented
I think it's failing because of the new output type of ``crop_region``.  I'll PR my test file with Marcelo's @zoccoler (merge in a merge... inception!)

2021-12-29 18:26 UTC, zoccoler commented
Thank you Robert @haesleinhuepf for these kind words ! :-)
Don't worry Tim @tdmorello, I will put your tests back and edit them to fit the new type of output 😃

2021-12-30 15:27 UTC, zoccoler commented
Hmm except for the ellipse, tests work locally, but not here in Github. Do you guys know what I am missing?

About the ellipse error, it fails due to unmatching mask and cropped data shapes. This also happens with polygons drawn close to the image border (`.to_masks()` generates larger (+1px in x/y) masks in these cases). This is a bug, I will open a new issue to deal with that separatedly from here.

2021-12-30 15:50 UTC, tdmorello commented
These changes fix `test_crop_function_nd`:

```
diff --git a/napari_crop/_tests/test_function.py b/napari_crop/_tests/test_function.py
index 5522eb0..2f28997 100644
--- a/napari_crop/_tests/test_function.py
+++ b/napari_crop/_tests/test_function.py
@@ -97,7 +97,7 @@ shape_data_ids = ["2x3_crop", "neg_crop", "big_crop", "poly_crop"]
     "shape_data,shape_type", zip(shape_data, shape_types), ids=shape_data_ids
 )
 
-def test_crop_function_nd(image_data, rgb, shape_data, shape_type,
+def test_crop_function_nd(layer_data, rgb, layer_type, shape_data, shape_type,
                           make_napari_viewer):
 
     viewer = make_napari_viewer()
@@ -117,7 +117,7 @@ def test_crop_function_nd(image_data, rgb, shape_data, shape_type,
     nlayers = len(viewer.layers)
 
     #  Get first tuple element (data) of first list element (LayerDataTuple)
-    cropped_data = crop_region(img_layer, shp_layer)[0][0]
+    cropped_data = crop_region(layer, shapes_layer)[0][0]
     viewer.add_image(cropped_data)
 
     assert len(viewer.layers) == nlayers + 1
```

Haven't looked into the ellipse param for `test_crop_function_values_2d` yet.

2021-12-30 16:16 UTC, zoccoler commented
> These changes fix `test_crop_function_nd`:

Thanks Tim! @tdmorello I have no idea how that got past 😅

2022-01-04 19:07 UTC, zoccoler commented
Hi guys,

I implemented some changes that I think fix #13 and #8 (also #6, which was already fixed before this last commit).

Basically I mapped the output from `.to_masks()` to the cropped data. Tests worked locally.
I also made irregular shape crops to be minimal by trimming zeros.

@haesleinhuepf please let me know if it works. If it does, from my side it is OK to merge.

2022-01-04 19:56 UTC, haesleinhuepf commented
Hi Marcelo @zoccoler ,

there is still one test failing (see below). It also fails locally on my  machine using `pytest --cov=napari_crop` from the root directory. Can you take another look please?

```
________________________________________ test_crop_function_values_2d[polygon] ________________________________________

make_napari_viewer = <function make_napari_viewer.<locals>.actual_factory at 0x000002392DD9C940>
shape = array([[0, 2],
       [4, 4],
       [4, 2],
       [2, 0]]), shape_type = 'polygon'
crop_expected = array([[ 0,  7,  0],
       [11, 12, 13],
       [16, 17, 18],
       [ 0, 22,  0]])

    @pytest.mark.parametrize(
        "shape,shape_type,crop_expected",
        zip(shapes, shape_types, crop_expected),
        ids=shape_types,
    )
    def test_crop_function_values_2d(make_napari_viewer, shape, shape_type,
                                     crop_expected):
        """Test that the cropped output is the expected array."""

        viewer = make_napari_viewer()
        img_layer = viewer.add_image(arr_2d)
        shapes_layer = viewer.add_shapes(shape, shape_type=shape_type)
        cropped_actual = crop_region(img_layer, shapes_layer)
        cropped_actual_arrays = [cropped[0] for cropped in cropped_actual][0]
>       assert np.array_equal(crop_expected, cropped_actual_arrays)
E       assert False
E        +  where False = <function array_equal at 0x0000023924978940>(array([[ 0,  7,  0],\n       [11, 12, 13],\n       [16, 17, 18],\n       [ 0, 22,  0]]), array([[ 0,  2,  0],\n       [ 6,  7,  0],\n       [11, 12, 13],\n       [ 0, 17, 18]]))
E        +    where <function array_equal at 0x0000023924978940> = np.array_equal

napari_crop\_tests\test_function.py:61: AssertionError
```

2022-01-04 21:33 UTC, zoccoler commented
Ok, could you please try again now?

2022-01-05 18:10 UTC, merged

2022-01-05 18:10 UTC, haesleinhuepf commented
Big thanks @zoccoler and @tdmorello :-)

2022-01-10 17:52 UTC, zoccoler commented
Close #13